#!/bin/bash
# Install remotes package in R
R -e "install.packages('remotes')"

# Install FlowR from GitHub using remotes
R -e "remotes::install_github('flowr-analysis/rstudio-addin-flowr')"

# Install additional R packages not covered in `environment.yml`
Rscript -e "if (!requireNamespace('qgraph', quietly = TRUE)) install.packages('qgraph', repos = 'http://cran.us.r-project.org')"
